version: "3"
services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - db
      - cache
    env_file: ./.env
    restart: always

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=pgdatabase  
      - POSTGRES_USER=pguser 
      - POSTGRES_PASSWORD=pgpassword  
    volumes:
      - db_data:/var/lib/postgresql/data 

  cache:
    image: redis:latest
    restart: always
  
volumes:
  db_data: